- hosts: localhost
  tasks:
    - name: read file
      ansible.builtin.set_fact:
#        data: '{{ lookup("ansible.builtin.file", "input_sample.txt") | list | map("int") }}'
        data: '{{ lookup("ansible.builtin.file", "input.txt") | list | map("int") }}'

    - name: default variables
      ansible.builtin.set_fact:
        disk: []

    - name: assemble disk layout
      ansible.builtin.set_fact:
        disk: |
          {%- for item in data -%}
            {%- set idx = loop.index - 1 -%}
            {%- if idx % 2 == 0 -%}
              {%- set _ = disk.append([(idx / 2) | int]*item) -%}
            {%- else -%}
              {%- set _ = disk.append(["."]*item) -%}
            {%- endif -%}
          {%- endfor -%}
          {{ disk | flatten }}

    - name: compact disk
      ansible.builtin.set_fact:
        disk: |
          {%- set non_empty = [] -%}
          {%- for block in disk -%}
            {%- if block != "." -%}
              {%- set _ = non_empty.append({ "block": block, "idx": loop.index-1 }) -%}
            {%- endif -%}
          {%- endfor -%}
          
          {%- for current_block in disk -%}
            {%- set idx = loop.index - 1 -%}
            {%- set non_empty_count = non_empty | length -%}
          
            {%- if current_block == "." and non_empty_count > 0 -%}
              {%- set last_non_empty = non_empty[non_empty_count-1] -%}
              {%- if last_non_empty.idx > idx -%}
                {%- set _ = non_empty.__delitem__(non_empty_count-1) -%}
                {%- set _ = disk.__setitem__(idx, last_non_empty.block) -%}
                {%- set _ = disk.__setitem__(last_non_empty.idx, ".") -%}
              {%- endif -%}
            {%- endif -%}
          
          {%- endfor -%}
          {{ disk }}

    - name: update checksum
      ansible.builtin.set_fact:
        sum: |
          {%- set sum = { "sum": 0 } -%}
          {%- for item in disk -%}
            {%- if item != "." -%}
              {%- set idx = loop.index - 1 -%}
              {%- set _ = sum.update({ "sum": sum.sum + item * idx }) -%}
            {%- endif -%}
          {%- endfor -%}
          {{ sum }}

    - debug:
        var: sum.sum